version: '3'

services:
  vote:
    image: punitganshani/aspnet-docker-vote
    container_name: voteapp
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - redis
    ports:
      - "8080:80"
    deploy:
      replicas: 5
      update_config:
        parallelism: 2
      restart_policy:
        condition: on-failure   
        delay: 10s
        max_attempts: 3
        window: 120s

  redis:
    image: redis
    container_name: redis
    entrypoint: redis-server --appendonly yes
    hostname: redis
    volumes:
      - redis-data:/data
    restart: always
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure   

volumes:
  redis-data:

